# Postgres in Docker tutorial: https://geshan.com.np/blog/2021/12/docker-postgres/
# free test db resource: https://www.elephantsql.com/plans.html
version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=fullstack_ts_db_user
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fullstack_ts_db
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
