services:
  - type: web
    name: fullstack-ts-client
    env: static
    buildCommand: pnpm run build-client
    staticPublishPath: services/client/dist
    envVars:
      - fromGroup: fullstack-ts-env-shared
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: fullstack-ts-server
    plan: free
    env: node
    buildCommand: pnpm run build-server
    startCommand: pnpm run start-server
    healthCheckPath: /healthz
    envVars:
      - fromGroup: fullstack-ts-env-shared
      - key: DATABASE_URL
        fromDatabase:
          name: fullstack-ts-db
          property: connectionString
    # buildFilter:
    #   paths:
    #     - services/server/**
    #     - packages/utilities/**

databases:
  - name: fullstack-ts-db
    plan: free
    postgresMajorVersion: 14
    ipAllowList: []

envVarGroups:
  - name: fullstack-ts-env-shared
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_ORIGIN
        value: https://fullstack-ts-server.onrender.com
      - key: PORT
        value: 5000
      - key: CLIENT_ORIGIN
        value: https://fullstack-ts-client.onrender.com
      - key: API_PREFIX
        value: /api
        # TODO(lt): add GOOGLE_CLIENT_ID in render dashboard
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: HUSKY
        value: 0
      - key: NODE_VERSION
        value: 18.12.1
      - key: SKIP_INSTALL_DEPS
        value: true
